# Generated by Django 5.2.7 on 2025-11-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0041_alter_pageurl_unique_together_pageurl_site_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoIsWhoPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("who_is_who_url", models.CharField(default="http://localhost:5173")),
                (
                    "locale",
                    models.CharField(
                        choices=[
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("fr", "Français"),
                        ],
                        default="de",
                    ),
                ),
                ("midata_group_index", models.CharField(default="2")),
                ("use_auth", models.BooleanField(blank=True, default=False)),
                ("auth_user", models.CharField(blank=True, default="")),
                ("auth_password", models.CharField(blank=True, default="")),
                ("cached_html", models.TextField(default="")),
                ("cached_stylesheet", models.TextField(default="")),
                ("cached_script", models.TextField(default="")),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
